### ISSUE TITLE
SCM002 - Add heroku deployment config and configure heroku deployment

### ISSUE THREAD

**Issue by scmojt** [scmojt/scmojt2018#2]
1. configure heroku for continues delivery
2. add heroku delivery config
3. add heroku environment variable = STAGING for PRODUCTION and QA
4. configure circleCI for heroku continues delivery

**Comment by yoyoktriwicaksono** [comment]
done

**Comment by yoyoktriwicaksono** [comment]
**Circle.yml**
`deployment:
  production:
    branch: master
    heroku:
      appname: scmojtproduction
  staging:
    branch: develop
    heroku:
      appname: scmojtqa
`

**Comment by yoyoktriwicaksono** [comment]
![image](https://user-images.githubusercontent.com/15881663/47479958-f2fa1f00-d858-11e8-8bb3-0a5608e8a521.png)

**Comment by yoyoktriwicaksono** [comment]
![image](https://user-images.githubusercontent.com/15881663/47479991-11601a80-d859-11e8-89df-55aea2cda467.png)

**Comment by yoyoktriwicaksono** [comment]
![image](https://user-images.githubusercontent.com/15881663/47480030-318fd980-d859-11e8-9e05-a0abdd452ce2.png)

**Comment by yoyoktriwicaksono** [comment]
![image](https://user-images.githubusercontent.com/15881663/47480051-44a2a980-d859-11e8-94eb-39705eaf0351.png)

**Comment by yoyoktriwicaksono** [comment]
![image](https://user-images.githubusercontent.com/15881663/47480067-52f0c580-d859-11e8-9a11-7f37e61507a8.png)

**Comment by yoyoktriwicaksono** [comment]
![image](https://user-images.githubusercontent.com/15881663/47480086-61d77800-d859-11e8-9267-f4e41624a6d8.png)
